### ISSUE TITLE
Sample data?

### ISSUE THREAD

**Issue by gibiansky** [wltrimbl/thumbnailpolish#2]
I saw the `thumbnailpolish` repository, and was wondering whether you could share some of the raw data you used when writing it. I'd like to experiment with writing my own basecalling software, but can't find any raw Illumina tiff/cif files available for download for testing. Do you have any I could use? Or know where I might be able to download some?

**Comment by wltrimbl** [comment]
The thumbnails are made form low-resolution diagnostic images intended for
display, not the real images.

I'm happy to share sets of thumbnails; a hiseq run has about 40 Gb of
thumbnail images in about 200,000 files.

The sequencing centers used to have access to tiff tiles but I do not think
these are in the output any more (illumina and the customers both are happy
enough that the data are turned into basecalls promptly--for exactly the
same reason that no one wants to keep the images from sanger capilaries).

However: basecaller refinements?  Really?  As a pedagogical exercise,
sounds great, it's a super interesting and relevant problem.  But academia
and industry solved the four-color base calling problem about six years
ago, and there is very little gain to be had by boosting some kind of
overall accuracy from 98% to 98.3%.  They had to solve lots of nuisance
problems like image registration and contrast adjustment.. it looks to me
an awful lot like a nicely solved problem.

If you are actually interested, I can look to see if there are still any
images at all.  If there aren't, you can try asking illumina, but I
wouldn't be optimistic.

Will Trimble
Argonne National Laboratory
trimble@anl.gov


On Wed, Nov 11, 2015 at 10:02 PM, Andrew Gibiansky <notifications@github.com

**Comment by gibiansky** [comment]
I'd like to do this purely for my own gratification :) I've never needed to do any sort of custom basecalling, the Illumina RTA software works and is configurable enough for all practical needs, so I agree that it's pretty much a solved problem.

If you could share thumbnail images and any raw images, that'd be really awesome. Doesn't have to be a huge amount of data – I'd be perfectly happy with just a few tiles and just a few consecutive cycles.

Thanks!

**Comment by wltrimbl** [comment]
Ok, so I looked through my sequencing center's archives, and I can only
find what appear to be full-resolution images for a single (miseq)
sequencing run (from 2014).

A sample of the apparently high-resolution images for 1 tile * 9 cycles * 4
colors is here (317 Mb):
http://mcs.anl.gov/~trimble/nodi/run140626_M02149_0118-sampleimages.zip

However, I can't confirm that the run didn't crash (and that's why we have
the high resolution images, they weren't cleaned up when the run finished),
and don't have any sequence data for it, much less known-ground truth data.

s_1_1108_g.tif TIFF 2944x2866 2944x2866+0+0 16-bit Grayscale

If you'd like the low resolution bundles of images, I get get those too.
Good luck..

W


On Wed, Nov 11, 2015 at 10:26 PM, Andrew Gibiansky <notifications@github.com

**Comment by gibiansky** [comment]
Thank you!
